var arrayLines = new Array();

for (var i = 1 ; i<=14 ; i++)
{
	arrayLines[i-1] = document.getElementById("au" + i);
}

var genDelay = 450;

var arrayText = [
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
">LIST PERSONNEL:",
"Michael Abrash",
"Mike Ambinder",
"Max Aristov",
"Ricardo Ariza",
"Gautam Babbar",
"Ted Backman",
"William Bacon",
"Jeff Ballinger",
"Ken Banks",
"Aaron Barber",
"Jeep Barnett",
"John Bartkiw",
"Mark Behm",
"Mike Belzer",
"Jeremy Bennett",
"Dan Berger",
"Yahn Bernier",
"Amanda Beste",
"Ken Birdwell",
"Derrick Birum",
"Mike Blaszczak",
"Iestyn Bleasdale-Sheperd",
"Steve Bond",
"Matt Boone",
"Michael Booth",
"Antoine Bourdon",
"Christopher Boyd",
"Jason Brashill",
"Charlie Brown",
"Jeff Brown",
"Tom Bui",
"Charlie Burgin",
"Andrew Burke",
"Augusta Butlin",
"Tobin Buttram",
"Liz Cambridge",
"Heather Campbell",
"Matt Campbell",
"Chris Carollo",
"Dario Casali",
"Matt Charlesworth",
"Pongthep Bank Charnchaichujit",
"Grégoire Cherlin",
"Chris Chin",
"Jess Cliffe",
"Phil Co",
"John Cook",
"Christen Coomer",
"Greg Coomer",
"Michael Coupland",
"Scott Dalton",
"Kerry Davis",
"Joe Demers",
"Ariel Diaz",
"Quintin Doroquez",
"Chris Douglass",
"Shanon Drone",
"Laura Dubuk",
"Mike Dunkle",
"Mike Durand",
"Marcus Egan",
"Zach Eller",
"Dhabih Eng",
"Brett English",
"Miles Estes",
"Chet Faliszek",
"Al Farnsworth",
"Dave Feise",
"Adrian Finol",
"Bill Fletcher",
"Adam Foster",
"Zachary Franks",
"Reuben Fries",
"Stephane Gaudette",
"Rich Geldreich",
"Vitaliy Genkin",
"Derrick Gennrich",
"Cayle George",
"Paul Graham",
"Chris Green",
"Bronwen Grimes",
"Chris Grinstead",
"John Guthrie",
"Aaron Halifax",
"Jeff Hameluck",
"Joe Han",
"Romy Hatfield",
"Nate Heller",
"Don Holden",
"Jason Holtman",
"Eric Hope",
"Gray Horsfield",
"Keith Huggins",
"Jim Hughes",
"Brandon Idol",
"Brian Jacobson",
"Lars Jensvold",
"Burton Johnsey",
"Erik Johnson",
"Rick Johnson",
"Adrian Johnston",
"Jakob Jungels",
"Neil Kaethler",
"Rich Kaethler",
"Steve Kalning",
"Kristopher Katz",
"Aaron Kearly",
"Emily Kent",
"Iikka Keränen",
"David Kircher",
"Eric Kirchmer",
"Zoid Kirsch",
"Tejeev Kohli",
"Peter Konig",
"Ted Kosmatka",
"Alden Kroll",
"Marc Laidlaw",
"Stefan Landvogt",
"Jeff Lane",
"Keith Lango",
"Tim Larkin",
"Liam Lavery",
"Jinwoo Lee",
"Isabelle Lemay",
"Tom Leonard",
"Justin Lesamiz",
"Jeff Lind",
"Jon Lippincott",
"Jane Lo",
"Matt Logue",
"Doug Lombardi",
"Richard Lord",
"Realm Lovejoy",
"Joe Ludwig",
"Scott Ludwig",
"Randy Lundeen",
"Roger Lundeen",
"Scott Lynch",
"Antonello Maddalena",
"Ido Magal",
"Nick Maggiore",
"Yasser Malaika",
"Connor Malone",
"Alexander Mark",
"Michael Marcus",
"John McCaskey",
"Patrick McClard",
"Noel McGinn",
"Hamish McKenzie",
"Gary McTaggart",
"Sergiy Migdalskiy",
"Jason Mitchell",
"Caroline Müller",
"Kyle Monroe",
"Mike Morasky",
"John Morello II",
"Chandler Murch",
"Jim Murray",
"Marc Nagel",
"Olivier Nallet",
"Arsenio N. Navarro II",
"Dina Nelson",
"Gabe Newell",
"Milton Ngan",
"Aaron Nicholls",
"Matt Nickerson",
"Andy Nisbet",
"Michael Avon Oeming",
"Martin Otten",
"Corey Peters",
"Jay Pinkerton",
"DJ Powers",
"Karen Prell",
"Matt Pritchard",
"Bay Raitt",
"Lindsay Randall",
"Alireza Razmpoosh",
"Tristan Reidford",
"Brandon Reinhart",
"Alfred Reynolds",
"Matt Rhoten",
"Mark Richardson",
"Garret Rickey",
"Dave Riller",
"Ted Rivera",
"Christian Rivers",
"Erik Robson",
"Joe Rohde",
"Elan Ruskin",
"Matthew Russell",
"Jason Ruymen",
"Phillip Saltzman",
"Michael Sartain",
"Dave Saunders",
"David Sawyer",
"Marc Scaparro",
"Thorsten Scheuermann",
"Wade Schin",
"Matthew Scott",
"Gregory Sedgwick",
"Aaron Seeler",
"Chris Shambaugh",
"Taylor Sherman",
"Joel Shoop",
"Ivan Simoncini",
"Justin Skinner",
"Eric Smith",
"Jacob J. Smith",
"Jeff Sorensen",
"David Speyrer",
"Kutta Srinivasen",
"Mellissa Stanfield",
"Jay Stelly",
"Jenny Stendahl",
"Mike Stevens",
"Eric Strand",
"Jonathan Sutton",
"Anna Sweet",
"Eric Tams",
"Ryan Thorlakson",
"Kelly Thornton",
"Paul G. Thuriot",
"Ray Ueno",
"Jeff Unay",
"Doug Valente",
"Bill Van Buren",
"Gabe Van Engel",
"Alex Vlachos",
"Robin Walker",
"Eric Wanless",
"Chad Weaver",
"Joshua Weier",
"Chris Welch",
"Thad Wharton",
"Karl Whinnie",
"Andrea Wicklund",
"Andrew Wolf",
"Erik Wolfpaw",
"Doug Wood",
"Matt T. Wood",
"Danika Wright",
"Matt Wright",
"Pieter Wycoff",
"Shawn Zabecki",
"Torsten Zabka",
"",
"",
"",
">VOICES:",
"Ellen McLain - GlaDOS, Turrets",
"Stephen Merchant - Wheatley",
"J.K Simmons - Cave Johnson",
"Joe Michaels - Announcer",
"Nolan North - Cores,",
"Defective Turrets",
"Dee Bradley Baker - Atlas,",
"P-Body",
"",
"",
"",
">THANKS FOR THE USE",
">OF THEIR FACE:",
"Alesia Glidewell - Chell",
"",
"",
"",
">SONGS",
"'Exile Vilify' by:",
"The National",
"",
"'Still Alive' by:",
"Jonathan Coulton",
"",
"'Want You Gone' by:",
"Jonathan Coulton",
"",
"",
"",
">VOICE RECORDING:",
"Pure Audio, Seattle, WA",
"",
"",
"",
">TRANSLATIONS:",
"SDL",
"",
"",
"",
">SPECIAL THANKS TO:",
"Alienware",
"ATI",
"Dell",
"Falcon Northwest",
"Havok",
"Sam Gray",
"Jamie Hunsdale",
"",
">PHOTO CREDIT OF EARTH:",
"NASA",
"      ",
"      ",
"      ",
"      ",
"      ",
"     ",
"    ",
"   ",
"  ",
" ",
"",
"",
"",
"",
];

var aIndex = 0;
var currChar = 0, currSpan = 0;

dispAuthors();

function dispAuthors ()
{
	for (var i = 0 ; i < 13 ; i++)
	{
		arrayLines[i].innerHTML = arrayText[aIndex + i];
	}
	
	spellLastLine();
}

function spellLastLine ()
{
	var currIndex = aIndex + 13;
	currChar = 0;
	arrayLines[13].innerHTML = "";
	for (var j = 1 ; j <= arrayText[currIndex].length ; j++)
	{
		arrayLines[13].innerHTML += "<span id=\"char" + j + "\">" + arrayText[currIndex].charAt(currChar) + "</span>";
		document.getElementById("char" + j).style.color = "transparent";
		currChar++;
	}

	currSpan = 1;

	var speller = setInterval(function()
	{
		if (currSpan <= arrayText[currIndex].length)
		{
			document.getElementById("char" + currSpan).style.color = "#302001";
			currSpan++;
		}
		else
		{
			clearInterval(speller);
			aIndex++;
			dispAuthors();
		}
	}, (genDelay/(arrayText[currIndex].length)));
	
}